#!/bin/bash

usage_short(){ echo "usage: $(basename $0) [-hl]" ; }
usage() {
	# eventually want to add [-u user] [-p path] and -s (system) options.
	usage_short
	echo -e "\t-h\tDisplay this help text"
	echo -e "\t-l\tInstall via Symlinks to these files instead of copying"
	echo -e "\t\t(Don't move this dir after, or you'll be sorry!)"
}

# should we do a backup? probably
perform_backup=yes

#set $PREFIX for install. This should match the PREFIX in bashrc.
PREFIX=$HOME/.local

# by default, we install by copying, so the user can delete this directory.
# installing by symlink is useful for development, and other purposes.
install="cp -a"

# the list of files to install. We have to prefix each with a '.' during install.
files=(
	bash_profile
	bashrc
	bash.d
)

# list of directories to make. This sets up $PREFIX to work right.
dirs=(
	bin
	etc
	include
	lib
	lib32
	opt
	sbin
	share
	src
)

while getopts ":hl" option; do
	case $option in
		h)	usage
			exit 0
			;;
		l)	install="ln -s"
			;;
		:)	echo "$(basename $0): option -$option requires an argument"
			usage_short
			exit 1
			;;
		?)	echo "$(basename $0): illegal option -- $option"
			usage_short
			exit 1
			;;
	esac
done

# First, backup any old bash configuration files so we don't lose them.
if [ $perform_backup ]; then
	backup=$(mktemp -d ~/.bash_backup.XXXXXX)
	for file in $HOME/.bash*; do
			mv $file $backup
	done
	mv $backup/.bash_history $HOME
	# don't leave an empty directory hanging around
	rmdir $backup 2>/dev/null || true
	mv $backup $HOME 2>/dev/null || true
fi

# install bashrc files
for file in ${files[@]}; do
	 $install $PWD/$file $HOME/.$file
done

# create prefixed home directories
for dir in ${dirs[@]}; do
	mkdir -p $PREFIX/$dir
done
